- name: Initial setup
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: install Python if needed
      raw: "[[ `type python --version 2> /dev/null` ]] || sudo apt-get install -y python-minimal"
      tags:
        - init

# - hosts: all
#   become: yes
#   gather_facts: true
#   tasks:
#     - name: print debug info
#       debug:
#         msg: "{{ (env == 'development') | ternary(ansible_default_ipv4.gateway, ipify_public_ip | default('')) }}"
#       tags:
#         - ttt


- name: create infra and deploy to the server
  hosts: all
  become: yes
  roles:
    - docker
    - kiosk
  tasks:
    - name: Reboot a slow machine that might have lots of updates to apply
      reboot:
        reboot_timeout: 3600
    