- name: run stack
  docker_compose:
    project_name: maksika2
    definition:
        version: '3'
        services:
            web:
              image: nginx
              ports:
              - "127.0.0.1:80:80"
              restart: unless-stopped
  tags:
    - compost