---
- name: Install requirements
  apt:
    name: "{{ docker_req_packages }}"
    state: present
    update_cache: true
  vars:
    docker_req_packages:
    - ca-certificates
    - apt-transport-https

- name: Add gpg key for docker
  apt_key:
    id: 0EBFCD88
    keyserver: "keyserver.ubuntu.com"
    state: present

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

- name: Install docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
  vars:
    docker_packages:
    - docker-ce
    - docker-compose

- name: Enable doker service
  service:
    name: docker
    state: started
    enabled: true

- include: docker-compose.yml
...